[package]
name = "ternilo-automation"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
ternilo-local.workspace = true
ternilo-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
ternilo-kernel.workspace = true
tempfile.workspace = true

[lints]
workspace = true
