[package]
name = "ternilo-extension"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
jsonschema.workspace = true
ternilo-kernel.workspace = true
ternilo-protocol.workspace = true
ternilo-rhai.workspace = true
linorun-core.workspace = true
linorun-macros.workspace = true
rhai.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tokio.workspace = true
wasmtime.workspace = true

[dev-dependencies]
ternilo-builtins.workspace = true

[lints]
workspace = true
