[package]
name = "ternilo-kernel"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
linorun-core.workspace = true
linorun-macros.workspace = true
serde_json.workspace = true
schemars.workspace = true
tokio.workspace = true
ternilo-protocol.workspace = true

[lints]
workspace = true
