[package]
name = "ternilo-builtins"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
agent-client-protocol.workspace = true
chrono.workspace = true
futures-util.workspace = true
jsonschema.workspace = true
nix.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
linorun-core.workspace = true
linorun-macros.workspace = true
reqwest.workspace = true
regex.workspace = true
rhai.workspace = true
rmcp.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
schemars.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-util.workspace = true
ternilo-kernel.workspace = true
ternilo-protocol.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio.workspace = true

[lints]
workspace = true
